### ISSUE TITLE
优化扫库的小想法（我很菜）

### ISSUE THREAD

**Issue by Ekkosun** [MisakaFxxk/MisakaF_Emby#1]
就是我们既然做了json的数据库的的话，是不是可以把数据库下发到用户手里面（不知道json数据库能不能给到用户），让用户在本地搭建响应扫库请求的服务（然后我们扫库的时候，用代理代理到本地的服务上），站内定时更新json数据库，需要扫库的时候我们通过下载的数据库，自己离线扫库。这种方法可行么（这只是我的想法，俺没有实践经验，抱歉

**Comment by MisakaFxxk** [comment]
能在服务端解决就不要把麻烦抛给用户。你这个想法理论没问题，但落地实现起来很麻烦，首先99%的用户不会这方面的知识，没法自己搭建json数据库。然后如果你想在用户端就分流，那必然需要qx之类的支持重写的软件，而服务端有nginx就可以轻易做到。其次这个数据库并不小，有些公益服资源量比较大，上G都有可能，这么大的数据库对于分发方式和用户端性能都有很高的要求。

**Comment by wfb2222wfb** [comment]
支持大佬为支持公益服的发展做出贡献
